# Generated by Django 5.1.4 on 2026-07-08 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("content", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("pretest", "Pre-test"),
                            ("posttest", "Post-test"),
                            ("quiz", "Quiz"),
                            ("usability", "Usability"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="content.module",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "total_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="assessments.assessment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("mcq", "Multiple Choice"),
                            ("likert", "Likert Scale"),
                        ],
                        max_length=20,
                    ),
                ),
                ("options", models.JSONField(blank=True, null=True)),
                (
                    "correct_answer",
                    models.CharField(
                        blank=True,
                        help_text="Null for Likert items (no correct answer).",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "dimension",
                    models.CharField(
                        choices=[
                            ("ethical_awareness", "Ethical Awareness"),
                            ("critical_evaluation", "Critical Evaluation"),
                            ("bias_recognition", "Bias Recognition"),
                            ("privacy_accountability", "Privacy & Accountability"),
                            ("responsible_use", "Responsible Use"),
                            ("ai_social_good", "AI for Social Good"),
                        ],
                        max_length=60,
                    ),
                ),
                ("question_order", models.SmallIntegerField()),
                (
                    "max_score",
                    models.DecimalField(decimal_places=2, default=1, max_digits=5),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="assessments.assessment",
                    ),
                ),
            ],
            options={
                "ordering": ["question_order"],
            },
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.TextField()),
                (
                    "item_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="assessments.attempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="assessments.question",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="assessment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("assessment_type", "quiz"), ("module__isnull", False)),
                    models.Q(
                        models.Q(("assessment_type", "quiz"), _negated=True),
                        ("module__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="assessment_module_iff_quiz",
                violation_error_message="A module must be set for quizzes only, and must be null for pretest/posttest/usability assessments.",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attempt",
            unique_together={("user", "assessment")},
        ),
        migrations.AlterUniqueTogether(
            name="response",
            unique_together={("attempt", "question")},
        ),
    ]
