# Generated by Django 5.1.4 on 2026-07-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="feedback_correct",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="feedback_incorrect",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="reverse_scored",
            field=models.BooleanField(default=False),
        ),
    ]
