# Generated by Django 5.1.4 on 2026-07-08 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                (
                    "sequence_no",
                    models.SmallIntegerField(
                        help_text="Ordering position in the curriculum (e.g. 1–6). Unique.",
                        unique=True,
                    ),
                ),
                ("summary", models.TextField(blank=True)),
                ("is_published", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["sequence_no"],
            },
        ),
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("situation_text", models.TextField()),
                ("scenario_order", models.SmallIntegerField()),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenarios",
                        to="content.module",
                    ),
                ),
            ],
            options={
                "ordering": ["scenario_order"],
            },
        ),
        migrations.CreateModel(
            name="ScenarioOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_text", models.TextField()),
                (
                    "consequence_text",
                    models.TextField(
                        help_text="Feedback shown after the option is chosen."
                    ),
                ),
                ("ethical_principle", models.CharField(max_length=160)),
                (
                    "dimension",
                    models.CharField(
                        choices=[
                            ("ethical_awareness", "Ethical Awareness"),
                            ("critical_evaluation", "Critical Evaluation"),
                            ("bias_recognition", "Bias Recognition"),
                            ("privacy_accountability", "Privacy & Accountability"),
                            ("responsible_use", "Responsible Use"),
                            ("ai_social_good", "AI for Social Good"),
                        ],
                        max_length=60,
                    ),
                ),
                (
                    "weight",
                    models.SmallIntegerField(
                        help_text="How ethically sound this choice is, 0–100."
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="content.scenario",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="scenario",
            name="depends_on_choice",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this scenario only unlocks for students who selected this option earlier. Null = always shown.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="triggers",
                to="content.scenariooption",
            ),
        ),
        migrations.CreateModel(
            name="ContentPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("body", models.TextField(help_text="Markdown content.")),
                ("page_order", models.SmallIntegerField()),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="content.module",
                    ),
                ),
            ],
            options={
                "ordering": ["page_order"],
                "unique_together": {("module", "page_order")},
            },
        ),
    ]
