# Generated by Django 5.1.4 on 2026-07-08 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="reflection_prompt",
            field=models.TextField(
                blank=True,
                help_text="The reflection question shown at the end of the module. Served by the reflection endpoint so the prompt is authored content, not hard-coded.",
            ),
        ),
    ]
